<?php

namespace GuiasDocentes\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConsultanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultanteRepository extends EntityRepository
{
    public function getGrupoById($id){
        $grupo=$this->find($id);
        return $grupo;
    }
        
    // public function findAllOrderedByName()
    // {
    //     return $this->getEntityManager()
    //                 ->createQuery('SELECT u FROM Acme\HelloBundle\Entity\User u
    //                                 ORDER BY u.name ASC')
    //                 ->getResult();
    // }
    public function countDistinctConsultantes(){
        $query =$this
        ->createQueryBuilder('c')
        ->select('DISTINCT c.email')
        ->getQuery()
        ->getResult();
        return count($query);
    }
}
