<?php

namespace GuiasDocentes\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConsultaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultaRepository extends EntityRepository
{
    public function countDistinctConsultas(){
        $query =$this
        ->createQueryBuilder('c')
        ->select('DISTINCT c.id')
        ->getQuery()
        ->getResult();
        return count($query);
    }
    
    public function getNumConsultasByMonth($year){
        // $meses = array('enero','febrero','marzo','abril','mayo','junio','julio', 'agosto','septiembre','octubre','noviembre','diciembre');
        // $i=0;
        // foreach ($meses as $mes){
        //     $i++;
        for ($i=1; $i<=12; $i++){
            $date_inf =new \DateTime('1-'.$i.'-'.$year);
            $date_sup = new \DateTime('31-'.$i.'-'.$year);
            $query = $this
            ->getEntityManager()
            ->createQuery("SELECT a FROM GuiasDocentesAppBundle:Consulta a WHERE a.fecha > :date_inf AND a.fecha <= :date_sup ")
            ->setParameter('date_inf', $date_inf)
            ->setParameter('date_sup', $date_sup);

            $num_consultas[$i] = count($query->getResult());     
        }
        return $num_consultas;
    }
    
    public function getConsultasByHilo($id_hilo){
        return $this->findBy(array('hiloid' => $id_hilo), array('fecha' => 'ASC'));
    }
}
