<?php

namespace GuiasDocentes\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PerfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilRepository extends EntityRepository
{
    /* Funcion que devuelve el conjunto de todos los perfiles ordenados por peso*/
    public function getAllOrderProfiles(){
        $perfiles = $this->findAll();
        usort($perfiles, array($this, "comparePerfiles"));
        return $perfiles;
    }
    
    /* funcion de comparacion de perfiles*/
    private function comparePerfiles($p1, $p2){
        if ( $p1->getOrden() > $p2->getOrden() ){
            return 1;
        }else{
            return -1;
        }
    }  
    
    
    // public function findAllOrderedByName()
    // {
    //     return $this->getEntityManager()
    //                 ->createQuery('SELECT u FROM Acme\HelloBundle\Entity\User u
    //                                 ORDER BY u.name ASC')
    //                 ->getResult();
    // }
}
