<?php

namespace GuiasDocentes\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalRepository extends EntityRepository
{
    
    public function getPersonalOrdered(){
        $query = $this->createQueryBuilder('p')
            ->Join('GuiasDocentesAppBundle:TematicaSoporte', 'ts', 'WITH', 'ts.personalEmail = p.email')
            ->where('ts.personalEmail = p.email')                
            ->orderBy("ts.orden");
        return $query;
    }
    
}
