<?php

namespace GuiasDocentes\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PerfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalRepository extends EntityRepository
{
    public function getAllPersonal(){
        $personales = $this->findAll();
        return $personales;
    }
    // public function getEnunciado(){
    //     return $this->getEntityManager()
    //         ->createQuery(
    //             "SELECT (po.enunciado)
    //             FROM GuiasDocentesAppBundle:TematicaSoporte po
    //             WHERE po.personalEmail = '$this->getEmail()'
    //             ORDER BY po.orden ASC"
    //         )
    //         ->getResult();
    // }
    public function getEnunciado(){
        $this->getEnunciado();
    }
    
}
