<?php

namespace GuiasDocentes\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PfRepository extends EntityRepository
{
    /* funcion que devuelve un array de pf activas para un grupo dado por su idetificador en orden creciente a su peso*/
    
    public function getCollectionPFByGroupOrdered($idGrupo){
        return $this->findBy(array('grupoid' => $idGrupo, 'habilitada' => '1'), array('orden' => 'ASC'));
    }
}
