<?php

namespace GuiasDocentes\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RespuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespuestaRepository extends EntityRepository
{
    
    public function getRespuestasByConsulta($id_consulta){
        return $this->findBy(array('consulta' => $id_consulta), array('fecha' => 'ASC'));
    }
}