GuiasDocentes\AppBundle\Entity\Grupo:
    type: entity
    table: Grupo
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: Nombre
    manyToMany:
        perfilNombre:
            targetEntity: Perfil
            cascade: {  }
            mappedBy: null
            inversedBy: grupo
            joinTable:
                name: perfil_grupo_order
                joinColumns:
                    -
                        name: Grupo_ID
                        referencedColumnName: ID
                inverseJoinColumns:
                    -
                        name: Perfil_Nombre
                        referencedColumnName: Nombre
            orderBy: null
    lifecycleCallbacks: {  }
