GuiasDocentes\AppBundle\Entity\GrupoSoporte:
    type: entity
    table: Grupo_Soporte
    indexes:
        fk_Grupo_Soporte_Administrador1_idx:
            columns:
                - Administrador_ID
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
            column: Nombre
    manyToOne:
        administrador:
            targetEntity: Administrador
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Administrador_ID:
                    referencedColumnName: ID
            orphanRemoval: false
    manyToMany:
        perfilNombre:
            targetEntity: Perfil
            cascade: {  }
            mappedBy: null
            inversedBy: grupoSoporte
            joinTable:
                name: grupo_soporte_has_perfil
                joinColumns:
                    -
                        name: Grupo_Soporte_ID
                        referencedColumnName: ID
                inverseJoinColumns:
                    -
                        name: Perfil_Nombre
                        referencedColumnName: Nombre
            orderBy: null
        tem치tica:
            targetEntity: Tem치tica
            cascade: {  }
            mappedBy: null
            inversedBy: grupoSoporte
            joinTable:
                name: grupo_soporte_has_tem치tica
                joinColumns:
                    -
                        name: Grupo_Soporte_ID
                        referencedColumnName: ID
                inverseJoinColumns:
                    -
                        name: Tem치tica_ID
                        referencedColumnName: ID
            orderBy: null
    lifecycleCallbacks: {  }
