GuiasDocentes\AppBundle\Entity\Grupo:
    type: entity
    table: Grupo
    indexes:
        fk_Grupo_Perfil1_idx:
            columns:
                - Perfil_Nombre
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: Nombre
    manyToOne:
        perfilNombre:
            targetEntity: Perfil
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Perfil_Nombre:
                    referencedColumnName: Nombre
            orphanRemoval: false
    lifecycleCallbacks: {  }
