GuiasDocentes\AppBundle\Entity\Personal:
    type: entity
    table: Personal
    id:
        email:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            id: true
            column: Email
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
            column: Nombre
        apellidos:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            column: Apellidos
        departamento:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
            column: Departamento
    lifecycleCallbacks: {  }
