GuiasDocentes\AppBundle\Entity\Respuesta:
    type: entity
    table: Respuesta
    indexes:
        fk_Respuesta_Consulta1_idx:
            columns:
                - Consulta_ID
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        texto:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: Texto
        fecha:
            type: datetime
            nullable: true
            comment: ''
            column: Fecha
    manyToOne:
        consulta:
            targetEntity: Consulta
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Consulta_ID:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
