GuiasDocentes\AppBundle\Entity\Rf:
    type: entity
    table: RF
    indexes:
        fk_RF_Personal1_idx:
            columns:
                - Personal_Email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        texto:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: Texto
        keywords:
            type: string
            nullable: true
            length: 25
            fixed: false
            comment: ''
            column: Keywords
    manyToOne:
        personalEmail:
            targetEntity: Personal
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Personal_Email:
                    referencedColumnName: Email
            orphanRemoval: false
    lifecycleCallbacks: {  }
