guias_docentes_app_homepage:
    path:     /
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:index }
    
guias_docentes_app_gfaq:
    path: /gfaq
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:gfaq }

guias_docentes_app_contacto:
    path: /gfaq/contacto
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:contacto }
    
guias_docentes_app_contacto_resume:
    path: gfaq/contacto/resume
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:resumeConsultante }
    
guias_docentes_app_historico_soporte:
    path: gfaq/historico_sop/idhilo={slug}idCon={token}
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:historico }

guias_docentes_app_historico_soporte_set_visto:
    path: gfaq/historico_sop/idhilo={slug}idCon={token}/setVisto/{consulta_id}
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:setVisto }
    
guias_docentes_app_historico_soporte_add_respuesta:
    path: gfaq/historico_sop/idhilo={slug}idCon={token}/addRespuesta
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:addRespuestaHilo }
    
guias_docentes_app_historico_soporte_add_consulta:
    path: gfaq/historico_sop/idhilo={slug}idCon={token}/addConsulta
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:addConsultaHilo }
    
# Admin Panel

guias_docentes_app_admin_panel_index:
    path: /admin
    defaults: { _controller: GuiasDocentesAppBundle:AdminPanel:index }
    
login:
    path:     /login
    defaults: { _controller: GuiasDocentesAppBundle:Security:login }
    
login_check:    
    pattern:   /login_check
    
logout:
    pattern:     /logout
    
# Admin Panel - Administrador
    
guias_docentes_app_admin_panel_create_admin:
    path:   /create
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:create }

# Admin Panel - Perfiles

guias_docentes_app_admin_panel_profiles_manage:
    path:   admin/profiles
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:profiles }
    
guias_docentes_app_admin_panel_get_support_group:
    path:   admin/profiles/getGroupSupport
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:GetSupportGroup }
    methods: GET
    
guias_docentes_app_admin_panel_set_profile:
    path:   admin/profiles/set
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:ProfileSet }
    
guias_docentes_app_admin_panel_create_profile:
    path:   admin/profiles/create
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:createProfile }
    
# Admin Panel - Grupos PF
    
guias_docentes_app_admin_panel_group_manag:
    path:   /groups
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:group }
    
guias_docentes_app_admin_panel_set_group:
    path:   groups/set
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:GroupSet }
    
guias_docentes_app_admin_panel_get_profiles:
    path:   groups/getProfiles
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:GetProfiles }
    methods: GET
    
guias_docentes_app_admin_panel_delete_group:
    path:   groups/delete
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:GroupDelete }
    
    
# Admin Panel - Preguntas Frecuentes

guias_docentes_app_admin_panel_pf_manage:
    path:   admin/pf
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:pf }
    
# guias_docentes_app_admin_panel_get_support_group:
#     path:   admin/profiles/getGroupSupport
#     defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:GetSupportGroup }
#     methods: GET
    
guias_docentes_app_admin_panel_set_pf:
    path:   admin/pf/set
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:PFSet }
    
guias_docentes_app_admin_panel_create_pf:
    path:   admin/pf/create
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:createPF }

# Admin Panel - Estadisticas
    
guias_docentes_app_admin_panel_get_Num_Consultas_By_Month:
    path:   admin/getNumConsultasByMonth
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:GetNumConsultasByMonth }
    methods: GET
    
guias_docentes_app_admin_panel_statics:
    path:   admin/statics
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:Statics }