# FAQ
guias_docentes_app_homepage:
    path:     /
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:index }


#Exceptions FAQ

# pageNotFoundFAQ:
#     pattern:  /{path}
#     defaults: { _controller: GuiasDocentesAppBundle:FAQ:pageNotFound, path: '' }
#     requirements:
#         path: .*
    
guias_docentes_app_gfaq:
    path: /gfaq
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:gfaq }

guias_docentes_app_contacto:
    path: /gfaq/contacto
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:contacto }
    
guias_docentes_app_contacto_resume:
    path: gfaq/contacto/resume
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:resumeConsultante }
    
guias_docentes_app_historico_soporte:
    path: gfaq/historico_sop/idhilo={slug}idCon={token}
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:historico }

guias_docentes_app_historico_soporte_set_visto:
    path: gfaq/historico_sop/idhilo={slug}idCon={token}/setVisto/{consulta_id}
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:setVisto }
    
guias_docentes_app_historico_soporte_add_respuesta:
    path: gfaq/historico_sop/idhilo={slug}idCon={token}/addRespuesta
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:addRespuestaHilo }
    
guias_docentes_app_historico_soporte_add_consulta:
    path: gfaq/historico_sop/idhilo={slug}idCon={token}/addConsulta
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:addConsultaHilo }
    
# Admin Panel

guias_docentes_app_admin_panel_index:
    path: /admin
    defaults: { _controller: GuiasDocentesAppBundle:AdminPanel:index }
    
login:
    path:     /login
    defaults: { _controller: GuiasDocentesAppBundle:Security:login }
    
login_check:    
    pattern:   /login_check
    
logout:
    pattern:     /logout
    
guias_docentes_app_admin_panel_mailer_action:
    path: admin/mail
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:mailerAdmin}
    
guias_docentes_app_admin_panel_recover_pass:
    path: /recover
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:recover}
    
guias_docentes_app_admin_panel_perfil:
    path: admin/perfil
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:perfil}
    
# Admin Panel - Administrador
    
guias_docentes_app_admin_panel_create_admin:
    path:   /create
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:create }

# Admin Panel - Perfiles

guias_docentes_app_admin_panel_profiles_manage:
    path:   admin/profiles
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:profiles }
    
guias_docentes_app_admin_panel_get_support_group:
    path:   admin/profiles/getGroupSupport
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:GetSupportGroup }
    methods: GET
    
guias_docentes_app_admin_panel_set_profile:
    path:   admin/profiles/set
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:ProfileSet }
    
guias_docentes_app_admin_panel_delete_profile:
    path:   admin/profiles/delete
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:ProfileDelete }
    
guias_docentes_app_admin_panel_create_profile:
    path:   admin/profiles/create
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:createProfile }
    
# Admin Panel - Grupos PF
    
guias_docentes_app_admin_panel_group_manag:
    path:   /groups
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:group }
    
guias_docentes_app_admin_panel_set_group:
    path:   groups/set
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:GroupSet }
    
guias_docentes_app_admin_panel_get_profiles:
    path:   groups/getProfiles
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:GetProfiles }
    methods: GET
    
guias_docentes_app_admin_panel_delete_group:
    path:   groups/delete
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:GroupDelete }

guias_docentes_app_admin_panel_create_group:
    path: admin/groups/create
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:createGroup }
    
    
# Admin Panel - Preguntas Frecuentes

guias_docentes_app_admin_panel_pf_manage:
    path:   admin/pf
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:pf }
    
guias_docentes_app_admin_panel_get_group:
    path:   admin/pf/getGroup
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:GetGroup }
    methods: GET
    
guias_docentes_app_admin_panel_set_pf:
    path:   admin/pf/set
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:PFSet }
    
guias_docentes_app_admin_panel_delete_pf:
    path:   admin/pf/delete
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:PFDelete }
    
guias_docentes_app_admin_panel_create_pf:
    path:   admin/pf/create
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:createPF }

# Admin Panel - Grupos de Soporte

guias_docentes_app_admin_panel_group_support_manag:
    path:   admin/groupSupport
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:SupportGroup }
    
guias_docentes_app_admin_panel_set_support_group:
    path:   admin/groupSupport/set
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:SupportGroupSet }
    
guias_docentes_app_admin_panel_delete_support_group:
    path:   admin/groupSupport/delete
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:SupportGroupDelete }

guias_docentes_app_admin_panel_create_support_group:
    path:   admin/groupSupport/create
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:createSupportGroup }

guias_docentes_app_admin_panel_get_profiles_grupos_soporte:
    path:   admin/groupSupport/getProfiles
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:GetProfilesSoporte }
    methods: GET


# Admin Panel - Tematica Soporte

guias_docentes_app_admin_panel_tematica_soporte_manage:
    path:   admin/tematicaSoporte
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:tematicaSoporte }
    
    
guias_docentes_app_admin_panel_set_tematica_soporte:
    path:   admin/tematicaSoporte/set
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:TematicaSoporteSet }
    
guias_docentes_app_admin_panel_delete_tematica_soporte:
    path:   admin/tematicaSoporte/delete
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:TematicaSoporteDelete }
    
guias_docentes_app_admin_panel_create_tematica_soporte:
    path:   admin/tematicaSoporte/create
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:createTematicaSoporte }
    
guias_docentes_app_admin_panel_get_personal:
    path:   admin/tematicaSoporte/getPersonales
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:getPersonales }
    methods: GET
    
# Admin Panel - Miembros de Soporte

guias_docentes_app_admin_panel_miembro_soporte_manage:
    path:   admin/miembroSoporte
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:miembroSoporte }
    
    
guias_docentes_app_admin_panel_set_miembro_soporte:
    path:   admin/miembroSoporte/set
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:miembroSoporteSet }
    
guias_docentes_app_admin_panel_delete_miembro_soporte:
    path:   admin/miembroSoporte/delete
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:miembroSoporteDelete }
    
guias_docentes_app_admin_panel_create_miembro_soporte:
    path:   admin/miembroSoporte/create
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:createMiembroSoporte }
    
# Admin Panel - Informes

guias_docentes_app_admin_panel_informe:
    path:   admin/informe
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:informe }

# Admin Panel - Estadisticas
    
guias_docentes_app_admin_panel_get_Num_Consultas_By_Month:
    path:   admin/getNumConsultasByMonth
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:GetNumConsultasByMonth }
    methods: GET
    
guias_docentes_app_admin_panel_statics:
    path:   admin/statics
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:Statics }
    
# Admin Panel - Limpiar

guias_docentes_app_admin_panel_clean:
    path: admin/clean
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:clean }

# PDF

guias_docentes_app_admin_panel_historial:
    path: admin/historial
    defaults: {_controller: GuiasDocentesAppBundle:AdminPanel:layoutPDF }

#Exceptions 

pageNotFoundAdminPanel:
    pattern:  /{path}
    defaults: { _controller: GuiasDocentesAppBundle:AdminPanel:pageNotFound, path: '' }
    requirements:
        path: .*