guias_docentes_app_homepage:
    path:     /
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:index }
    
guias_docentes_app_gfaq:
    path: /gfaq
    defaults: { _controller: GuiasDocentesAppBundle:FAQ:gfaq }