services:
#    guias_docentes_app.example:
#        class: GuiasDocentes\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    app.twig_extension:
        class: GuiasDocentes\AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }